FROM node:22-alpine AS base

WORKDIR /app
ENV CI=true

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml .
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

CMD ["node", "dist/index.js"]