FROM node:22-alpine AS builder

WORKDIR /app
ENV CI=true

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml .
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

FROM node:22-alpine AS runner

WORKDIR /app
COPY --from=builder /app/dist/ ./dist/
COPY --from=builder /app/node_modules ./node_modules

CMD ["node", "dist/index.js"]