/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnotherPageRouteImport } from './routes/another-page'
import { Route as IndexRouteImport } from './routes/index'

const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/another-page',
  path: '/another-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/another-page': typeof AnotherPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/another-page': typeof AnotherPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/another-page': typeof AnotherPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/another-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/another-page'
  id: '__root__' | '/' | '/another-page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherPageRoute: typeof AnotherPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/another-page': {
      id: '/another-page'
      path: '/another-page'
      fullPath: '/another-page'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherPageRoute: AnotherPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
