/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Example3RouteImport } from './routes/example-3'
import { Route as Example2RouteImport } from './routes/example-2'
import { Route as Example1RouteImport } from './routes/example-1'
import { Route as IndexRouteImport } from './routes/index'

const Example3Route = Example3RouteImport.update({
  id: '/example-3',
  path: '/example-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Example2Route = Example2RouteImport.update({
  id: '/example-2',
  path: '/example-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Example1Route = Example1RouteImport.update({
  id: '/example-1',
  path: '/example-1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example-1': typeof Example1Route
  '/example-2': typeof Example2Route
  '/example-3': typeof Example3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example-1': typeof Example1Route
  '/example-2': typeof Example2Route
  '/example-3': typeof Example3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example-1': typeof Example1Route
  '/example-2': typeof Example2Route
  '/example-3': typeof Example3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/example-1' | '/example-2' | '/example-3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/example-1' | '/example-2' | '/example-3'
  id: '__root__' | '/' | '/example-1' | '/example-2' | '/example-3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Example1Route: typeof Example1Route
  Example2Route: typeof Example2Route
  Example3Route: typeof Example3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/example-3': {
      id: '/example-3'
      path: '/example-3'
      fullPath: '/example-3'
      preLoaderRoute: typeof Example3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-2': {
      id: '/example-2'
      path: '/example-2'
      fullPath: '/example-2'
      preLoaderRoute: typeof Example2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-1': {
      id: '/example-1'
      path: '/example-1'
      fullPath: '/example-1'
      preLoaderRoute: typeof Example1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Example1Route: Example1Route,
  Example2Route: Example2Route,
  Example3Route: Example3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
