/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithSuspenseQueryRouteImport } from './routes/with-suspense-query'
import { Route as BasicLoaderRouteImport } from './routes/basic-loader'
import { Route as IndexRouteImport } from './routes/index'

const WithSuspenseQueryRoute = WithSuspenseQueryRouteImport.update({
  id: '/with-suspense-query',
  path: '/with-suspense-query',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicLoaderRoute = BasicLoaderRouteImport.update({
  id: '/basic-loader',
  path: '/basic-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-loader': typeof BasicLoaderRoute
  '/with-suspense-query': typeof WithSuspenseQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-loader': typeof BasicLoaderRoute
  '/with-suspense-query': typeof WithSuspenseQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-loader': typeof BasicLoaderRoute
  '/with-suspense-query': typeof WithSuspenseQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/basic-loader' | '/with-suspense-query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/basic-loader' | '/with-suspense-query'
  id: '__root__' | '/' | '/basic-loader' | '/with-suspense-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicLoaderRoute: typeof BasicLoaderRoute
  WithSuspenseQueryRoute: typeof WithSuspenseQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/with-suspense-query': {
      id: '/with-suspense-query'
      path: '/with-suspense-query'
      fullPath: '/with-suspense-query'
      preLoaderRoute: typeof WithSuspenseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-loader': {
      id: '/basic-loader'
      path: '/basic-loader'
      fullPath: '/basic-loader'
      preLoaderRoute: typeof BasicLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicLoaderRoute: BasicLoaderRoute,
  WithSuspenseQueryRoute: WithSuspenseQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
